baseURL = "https://tokyodcs.tane.website/"
#baseURL = "/"
defaultContentLanguage = "ja"
languageCode = "ja-jp"
title = "東京大学 理学部情報科学科/大学院情報理工学系研究科コンピュータ科学専攻"
theme = "hugo-issu" 

[languages]
  [languages.ja]
    languageName = "Japanese"
    languageCode = 'ja-JP'
    title = "東京大学 理学部情報科学科/大学院情報理工学系研究科コンピュータ科学専攻"
    weight = 1
    contentDir = "content/ja"
    dateFormat = "2006年1月2日"
    description = "東京大学 理学部情報科学科/東京大学 大学院情報理工学系研究科 コンピュータ科学専攻"
    keywords =  "東京大学,理学部,情報科学科,大学院,情報理工学系研究科,コンピュータ科学専攻"

  [languages.en]
    languageName = "English"
    languageCode = 'en'
    title = "Department of Computer Science, The University of Tokyo"
    weight = 2
    contentDir = "content/en"
    dateFormat = "Jan. 2, 2006"
    description = "Department of Information Science, Faculty of Science, The University of Tokyo / Department of Computer Science, Graduate School of Information Science and Technology, The University of Tokyo"
    keywords =  "The University of Tokyo, Faculty of Science, Department of Information Science, Graduate School of Information Science and Technology, Department of Computer Science"


[taxonomies]
news = "news"
lecture = "lecture"
#tag = "tags"
#category = "categories"
#series = "series"
#class = "class"

#categories02 = "Cat02"

[outputs]
page = [ "HTML"]
home = [ "HTML"]
news = [ "HTML"]
lecture = [ "HTML"]
#taxonomy = [ "HTML"]
#taxonomyTerm = [ "HTML"]

[markup]
    [markup.tableOfContents]
        endLevel = 4
        ordered = true
        startLevel = 2
